### ISSUE TITLE
Azure 3.x SDK compatibility?

### ISSUE THREAD

**Issue by JayVDZ** [netripper/Ms.Azure.Logging#1]
First off, thank-you for writing this... Is this compatible with the new 3.x version of the Azure SDK? I'm trying to switch my solution which uses Log4Net with SQL Server okay over to this and I'm not getting anything in my storage account, and Log4Net being Log4Net, I get no information to help, even with the Log4Net debug mode enabled.

I use Blob Storage okay as well with the existing 3.x SDK package in the solution.

**Comment by martijns** [comment]
The most recent version of the Azure SDK is 2.2. There is no 3.x version.

The code was updated a while ago to work with >2.0. You might need a bindingredirect in your .config to make it work with newer versions of the SDK. If you use the code instead, it should compile and work.

I'll check compatibility with SDK 2.2 in the near future. I'm still working with SDK 2.1 myself.

**Comment by adamjbradley** [comment]
Actually there is https://www.nuget.org/packages/WindowsAzure.Storage/3.1.0 and I just came across this issue. I updated to Storage Client 3.x and it compiles ok! There are no unit tests so until I get some time to include log4net logging back into my project (a few days I suspect) we won't know for sure.

//Adam

**Comment by adamjbradley** [comment]
Seems to work.
//Adam

**Comment by adamjbradley** [comment]
Actually... it doesn't

**Comment by martijns** [comment]
I've updated the package to work with Azure SDK 2.4 (Storage 4.3.0). I'm not using 2.5 myself, but I doubt there are compatibility issues there.

I did notice the WCF Data Services for Azure Table Storage is becoming obsolete. That might become an issue in the future.
